---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: minikube-namespaces
  namespace: kube-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/luishmg/minikube-namespaces.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minkube-namespaces
  namespace: kube-system
spec:
  interval: 10m0s
  path: ./deploy/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: minikube-namespaces
