---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse
  labels:
    team: DevOps
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: concourse
  namespace: flux-system
spec:
  interval: 1m
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
spec:
  chart:
    spec:
      chart: concourse
      sourceRef:
        kind: HelmRepository
        name: concourse
        namespace: flux-system
      version: 16.1.16
  interval: 1m0s
  values:
    fullnameOverride: concourse
    concourse:
      web:
        auth:
          mainTeam:
            localUser: admin 
        externalUrl: http://concourse-ci.k8s.stg.lab.internal
        bindPort: 80
        tls:
          enabled: false
          bindPort: 443
        enabled: true
      kubernetes:
        keepNamespace: false
      # worker:
      #   kind: Deployment
      #   baggageclaim:
      #     driver: btrfs
      secrets:
        localUsers: admin:$2y$10$7CiEp1/hCbDpgTvo2m478e9ZvzclxXr3tOPXzYqvUr9GMsBnEZXcS
      #   workerKey: |
      #     -----BEGIN RSA PRIVATE KEY-----
      #     data data data data
      #     -----END RSA PRIVATE KEY-----
      #   workerKeyPub: ssh-rsa datadatadata comment
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: concourse-internal
  namespace: concourse
spec:
  hosts:
  - "concourse-ci.k8s.stg.lab.internal"
  gateways:
  - istio-system/gateway-internal
  http:
  - route:
    - destination:
        host: concourse-web
        port:
          number: 8080
