---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse
  labels:
    team: DevOps
    istio-injection: enable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: concourse
  namespace: flux-system
spec:
  interval: 1m
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
spec:
  chart:
    spec:
      chart: concourse
      sourceRef:
        kind: HelmRepository
        name: concourse
        namespace: flux-system
      version: 16.1.16
  interval: 1m0s
  values:
    fullnameOverride: concourse
    concourse:
      web:
        enabled: true
        externalUrl: "concourse-ci.k8s.stg.lab.internal"
        kubernetes:
          keepNamespace: false
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: concourse-internal
  namespace: concourse
spec:
  hosts:
  - "concourse-ci.k8s.stg.lab.internal"
  gateways:
  - istio-system/gateway-internal
  http:
  - route:
    - destination:
        host: concourse-web
        port:
          number: 8080
