---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster-extensions
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/luishmg/flux-lab-cluster-extensions.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets-cluster-resources
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/lab-stg/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/common/rook-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/lab-stg/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/tekton
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shipwright
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/shipwright
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: namespaces-and-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/luishmg/minikube-namespaces.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces-and-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: namespaces-and-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: concourse
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/adm/concourse
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
