---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster-extensions
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/luishmg/flux-lab-cluster-extensions.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/common/rook-storage/01-rook-crds.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-common
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/common/rook-storage/02-common.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/common/rook-storage/03-operator.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rook-ceph-storage-class
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/common/rook-storage-class
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets-deployment
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/lab-stg/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-resources
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/istio-resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/tekton
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shipwright
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/shipwright
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/stg/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minkube-namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: minikube-namespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: concourse
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environment/adm/concourse
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-extensions
