---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-test
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/luishmg/app-gitops-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-test
  namespace: web-store
spec:
  interval: 10m0s
  path: ./deploy/stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-test
    namespace: flux-system
