---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rook-release
  namespace: rook-ceph
spec:
  interval: 1m
  url: https://charts.rook.io/release
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: rook-ceph
#   namespace: rook-ceph
# spec:
#   chart:
#     spec:
#       chart: rook-ceph
#       sourceRef:
#         kind: HelmRepository
#         name: rook-release
#         namespace: rook-ceph
#       version: 1.8.3
#   interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      version: 1.8.3
  interval: 1m0s
  # values:
  #   operatorNamespace: rook-ceph
