---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    team: DevOps
    istio-injection: disable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rook-release
  namespace: rook-ceph
spec:
  interval: 1m
  url: http://192.168.50.1:8000/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      version: 1.8.3
  interval: 1m0s
