---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gocd
  namespace: gocd
spec:
  interval: 1m0s
  url: https://gocd.github.io/helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gocd
  namespace: gocd
spec:
  chart:
    spec:
      chart: gocd
      sourceRef:
        kind: HelmRepository
        name: gocd
      version: 1.40.2
  interval: 1m0s
