---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gocd-internal
  namespace: gocd
spec:
  hosts:
  - "gocd.k8s.stg.lab.internal"
  gateways:
  - istio-system/gateway-internal
  http:
  - route:
    - destination:
        host: gocd-server
        port:
          number: 8153
